spring.application.name=leave-tracker

# DB configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/leave_tracker_db
spring.datasource.username=postgres
spring.datasource.password=system

spring.jpa.hibernate.ddl-auto=update

# To see all the sql statements run by hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true